name: Test Rest API
on: workflow_dispatch
jobs:
    run-and-test:
        name: run and test
        runs-on: ubuntu-latest
        steps:

          - name: Pull docker image
            run: docker pull coherentsolutions/rest-training:2.0

          - name: Run application from Docker image
            run: docker run -d -p 49000:8082 coherentsolutions/rest-training:2.0
          
          - uses: actions/checkout@v4
          - name: Setup .NET Core
            uses: actions/setup-dotnet@v3
            with:
                dotnet-version: 7.0.x

          - name: Install dependencies
            run: dotnet restore
      
          - name: Build
            run: dotnet build --configuration Release --no-restore
    
          - name: Test
            run: dotnet test --no-restore --verbosity normal

          - name: Load test report history
            uses: actions/checkout@v3
            if: always()
            continue-on-error: true
            with:
                ref: gh-pages1
                path: gh-pages1

          - name: Build test report
            uses: simple-elf/allure-report-action@v1.7
            if: always()
            with:
              gh_pages: gh-pages1
              allure_history: allure-history
              allure_results: bin/Debug/net7.0/allure-results

          - name: Publish test report
            uses: peaceiris/actions-gh-pages@v3
            if: always()
            with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              publish_branch: gh-pages1
              publish_dir: allure-history
